drone_init:
  x: -8
  y: -2.0
  z: 0

target_init:
  x: 0
  y: 0
  z: 0
  vx: 1.0
  vy: 0
  vz: 0

sim:
  dt: 0.05
  T: 10.0

estimator:
  horizon: 10

controller:
  kp: 1.0
  ki: 0.2
  kd: 0.2
  desired_distance: 4.0

world:
  grid:
    x_min: -12.5
    x_max:  12.5
    y_min: -12.5
    y_max:  12.5
  obstacles:
    - x: -2
      y: 0
      size: 1
    - x: 2
      y: 1
      size: 1